# name: Pipeline with Build and Jest Test in 2 Jobs

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Install dependencies
#         run: npm install
#       - name: Save node_modules and build folder as artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: build-artifacts
#           path: |
#             node_modules
#             .next # Falls du Next.js nutzt, andernfalls den entsprechenden Build-Ordner angeben

#   tests:
#     runs-on: ubuntu-22.04
#     needs: build # Test-Job wartet, bis der Build-Job erfolgreich ist
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Install dependencies
#         run: npm install
#       - name: Run test
#         run: npm test

name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  jest:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.12.1
          cache: pnpm

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Test with Jest
        run: npm jest --silent --maxWorkers=2
