name: Pipeline with Build and Jest Test in 2 Jobs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Save node_modules and build folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            node_modules
            .next # Falls du Next.js nutzt, andernfalls den entsprechenden Build-Ordner angeben

  tests:
    runs-on: ubuntu-22.04
    needs: build # Test-Job wartet, bis der Build-Job erfolgreich ist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
